server:
  port: 8080

spring:
  application:
    name: takeout
  redis:
    host: localhost
    port: 6379
    database: 0 #操作0号数据库
    jedis:
      # redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大堵塞时间
        max-idle: 4 # 连接池中最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存过期时间
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout
      username: root
      password: 102786
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: classpath:backend/** classpath:front/**

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    将字段名按驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true

takeout:
  path: E:\img\ # 图片在服务器上存放的路径

